### ISSUE TITLE
Carousels on Felix

### ISSUE THREAD

**Issue by theastralj** [BraveUX/website#140]
@callmecavs changed this issue to be for Felix only, since its the only case with carousels.  the other cases have other data visualization enhancements that will be documented in separated

**Comment by callmecavs** [comment]
prototype's been implemented, with all that good good (init each carousel right before its scrolled into view, lazy load images, pause on hover, etc).

## let's talk ux specifics:

- [ ] dots and/or arrows (dots in proto)
- [ ] automatically rotate through the slides?  (yes in proto, 2.5s between each)

Most importantly is **what sections do we want to make carousels**, and **do we have the source files/images available**. don't need the answers to the above to start adding in the other images and stuff, all carousels follow one global set of options

**Comment by callmecavs** [comment]
# FieldOne Progress

**Comment by callmecavs** [comment]
implemented, with all the goodness above, plus:

* init each carousel right before its scrolled into view
* lazy load images
* pause on hover

**Comment by callmecavs** [comment]
need to test this on actual mobile devices (ipad, iphone) before going live with it

**Comment by callmecavs** [comment]
merged into #155
