### ISSUE TITLE
Copyright is out of date 

### ISSUE THREAD

**Issue by leefinkel** [BraveUX/website#160]
Please change footer from 2014 > 2015.

**Comment by jaxgeller** [comment]
Fixed on master, but going to wait for tomorrow to ftp, dont want to push breaking changes.

**Comment by callmecavs** [comment]
this fix is live now, went live with the new work landing and contact pages

![screenshot 2015-01-13 13 03 06](https://cloud.githubusercontent.com/assets/2293641/5725850/8f646aec-9b24-11e4-8dfd-2f3df60b9198.png)
