### ISSUE TITLE
Contact page - tablet responsive - there's no color differentiation between content areas

### ISSUE THREAD

**Issue by kelaine** [BraveUX/website#161]
Should there be the grey/white striping like on full-size?
![screen shot 2015-01-12 at 4 37 40 pm](https://cloud.githubusercontent.com/assets/9937697/5711554/781f4f6a-9a79-11e4-8b09-a5dd89ba050f.png)

**Comment by callmecavs** [comment]
per @cpallen - lets make the middle section (visit us) gray
