### ISSUE TITLE
Work landing - the image should be larger relative to the size of the text

### ISSUE THREAD

**Issue by kelaine** [BraveUX/website#163]
This should be fixed for all images on the landing page (although FieldOne looks correct), but a representative image is attached
![screen shot 2015-01-12 at 4 51 19 pm](https://cloud.githubusercontent.com/assets/9937697/5711820/6997536e-9a7b-11e4-9bae-1cbb400cbb80.png)

**Comment by callmecavs** [comment]
because the site is full width, it makes the most sense for these images to be sized as a percentage of their container.  they were set to 50%, i bumped them all up to 60%
