### ISSUE TITLE
Work landing - CTA button text shouldn't be bold

### ISSUE THREAD

**Issue by kelaine** [BraveUX/website#164]
![screen shot 2015-01-12 at 4 56 12 pm](https://cloud.githubusercontent.com/assets/9937697/5711902/093fc78e-9a7c-11e4-814b-494fe861320e.png)

**Comment by callmecavs** [comment]
per @cpallen we're good to go here. all uses of Trade Gothic (such as this one) across the site have been set at 600 font weight, disregard the mockup in this case
