### ISSUE TITLE
Homepage - wrong font

### ISSUE THREAD

**Issue by kelaine** [BraveUX/website#166]
![screen shot 2015-01-12 at 5 00 58 pm](https://cloud.githubusercontent.com/assets/9937697/5711979/b14bf5ce-9a7c-11e4-92c9-46204ae42e2a.png)

**Comment by callmecavs** [comment]
@jaxgeller outline the text before exporting from illustrator.  not sure if this maybe has to do with the stroke attributes you were playing with to get vivus working?

**Comment by callmecavs** [comment]
@kelaine this is because our fonts from typography.com don't load on our test urls. on the staging site you'll see the font is correct
