### ISSUE TITLE
Homepage work section - alignment of text and images is incorrect

### ISSUE THREAD

**Issue by kelaine** [BraveUX/website#171]
width should be divided in two equal sections, one for image and the other for text.  Text should be left-aligned when on the right of the page and right-aligned when on the left of the page.  FYI - It was previously correct in the work landing page on the staging site.
![screen shot 2015-01-12 at 5 15 34 pm](https://cloud.githubusercontent.com/assets/9937697/5712264/cf991096-9a7e-11e4-83b0-e889d2eebf9e.png)

**Comment by jaxgeller** [comment]
fixed in 590283003e1ccbad35e5f962aee9f6f79a0522a4

**Comment by callmecavs** [comment]
this was resolved before it was pushed yesterday
