### ISSUE TITLE
Homepage - work section - should NOT have the prev/next case tabs (those are just for individual case studies)

### ISSUE THREAD

**Issue by kelaine** [BraveUX/website#172]
The mockup shows these, but it should not

**Comment by jaxgeller** [comment]
fixed in 8b6b674

**Comment by callmecavs** [comment]
only the case studies have these now. prev/next buttons follow the order on the work landing page (i.e. state of obesity - next goes to wedding wire, previous goes to felix).

they also wrap, so for felix, previous goes to fieldone, and for fieldone next goes to felix
