### ISSUE TITLE
Main call to action does nothing if JavaScript doesn't load

### ISSUE THREAD

**Issue by dracos** [BraveUX/website#185]
"Let's see it" is a <a href="https://github.com/BraveUX/website/blob/8c669053e9c8995aae4c48318b835573745f8929/src/views/index.ejs#L45">link to `#`</a>, so does nothing if the JavaScript has failed to load, errors, or <a href="http://kryogenix.org/code/browser/everyonehasjs.html">anything else</a> – I also have invisible scrollbars so just assumed the page was broken. It should be an internal link to `#whatever` with `whatever` existing as an ID or an `a name`. The back button would also then work to take you back after clicking a link.

**Comment by ekfuhrmann** [comment]
Each section has been given an `id` which the anchor tags now reference.  In addition I've added image placeholders when `noscript` is enabled.

**Comment by ekfuhrmann** [comment]
An `ID` tag has been added for the section the content is supposed to jump to and the `href` now directs to the appropriate section.
