### ISSUE TITLE
Internal links on /approach do nothing without JavaScript

### ISSUE THREAD

**Issue by dracos** [BraveUX/website#187]
Similar to #185, all the next links e.g. https://github.com/BraveUX/website/blob/8c669053e9c8995aae4c48318b835573745f8929/src/views/approach.ejs#L66 take you back to the top of the page.

**Comment by ekfuhrmann** [comment]
Each section has been given an `id` tag which the anchor tags now reference. In addition I've added image placeholders when `noscript` is enabled.
