### ISSUE TITLE
Careers more information unviewable without JavaScript

### ISSUE THREAD

**Issue by dracos** [BraveUX/website#188]
On /careers, the more information is hidden by default and the links to view it e.g. https://github.com/BraveUX/website/blob/8c669053e9c8995aae4c48318b835573745f8929/src/views/careers.ejs#L26 don't work. The information should all be viewable by default, hidden only if JavaScript is available to make the interested links work.

**Comment by ekfuhrmann** [comment]
A `<noscript>` has been added to expand the content in the case the user has JS disabled.  In addition I've also removed the empty anchor as it doesn't serve semantic purposes and replaced it as a `button` element.

**Comment by dracos** [comment]
Thanks for the change, but note this doesn't properly fix the issue – if you're on a browser that has JavaScript switched on, but your JavaScript fails to load for whatever reason (say the jQuery CDN is unavailable briefly, it happens), then the noscript won't run and the script won't run, and the content will be invisible. A better way to do it would be to have the style visible by default and then in the same JavaScript that sets up the toggle do the hiding (or for performance e.g. set a js class in the header and use that in your CSS to hide).

(Ideally, you'd only have the buttons showing if the JS runs, because they're not doing anything otherwise.)
